---
- hosts: localhost
  vars:
    os_username: jmyles
    git_name: jMyles
    email_address: justin@justinholmes.com
  tasks:
    - name: Set default git identity
      become_user: "{{os_username}}"
      become: yes
      shell: 'git config --global user.email "{{email_address}}"; git config --global user.name "{{git_name}}"'
    - name: Add Signal Keyring
      apt_key:
        url: https://updates.signal.org/desktop/apt/keys.asc
    - name: Add Docker Keyring
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    - name: Add repos
      apt_repository:
        repo: "{{ item }}"
      loop:
        - ppa:libretro/stable
        - "deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main"
        - "deb [arch=amd64] https://download.docker.com/linux/ubuntu disco stable"
#        - ppa:openshot.developers/ppa
#        - ppa:unit193/encryption
      register: repos
    - name: Update apt cache
      apt:
        update_cache: yes
      when: repos.changed
    - name: Install apt packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - gnome-tweaks
        - signal-desktop
        - git
        - gimp
        - htop
        - sshfs
        - ubuntu-restricted-extras
        - va-driver-all
        - vainfo
        - libva2
        - gstreamer1.0-libav
        - gstreamer1.0-vaapi
        - vlc
        - python3-pip
        - lsb-release
        - apt-transport-https
        - gdmap
        - inkscape
        - retroarch*
        - libgl1-mesa-glx:i386
        - openshot-qt
        - build-essential
        - gcc
        # - veracrypt
        - guvcview
        - chromium-browser
        - samba
        - net-tools
        - smbclient
        - adb
        - audacity
        - sonic-visualiser
        - macchanger
        - nmap
        - gparted
        - mesa-utils
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - uidmap
        - texlive
        - texlive-full
        - cmake
        - flatpak
    - name: Install authy snap
      community.general.snap:
        name:
          - authy
    - name: Add the flathub flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user
    - name: Install Telegram via flatpak
      community.general.flatpak:
        name: org.telegram.desktop
        state: present
    - name: Remove Things
      apt:
        name: "{{ packages }}"
        state: absent
        purge: yes
      vars:
        packages:
        - rhythmbox
        - ubuntu-web-launchers
        - gnome-orca
    - name: Install pip3 packages
      pip:
        executable: pip3
        name:
          - ipython
          - requests
          - ansible
          - pipenv
          - youtube-dl
          - magic-wormhole
    - name: Install PyCharm Pro
      snap:
        classic: yes
        name: pycharm-professional
    - name: Delete Amazon Stuff
      file:
        path: /usr/share/applications/ubuntu-amazon-default.desktop
        state: absent
    - name: Delete more Amazon Stuff
      file:
        path: /usr/share/unity-webapps/userscripts/unity-webapps-amazon
        state: absent


# veracrypt, openshot, add ssh key to github


