---
- hosts: localhost
  vars:
    github_username: jMyles
    os_username: jmyles
  tasks:
    - name: Clone github repos
      become_user: "{{os_username}}"
      become: yes
      git:
        repo: git@github.com:{{item}}.git
        dest: ~/projects/{{item}}
        remote: upstream
        key_file: ~/.ssh/id_rsa
        accept_hostkey: yes
        update: no
      loop:
        - JustinHolmesMusic/justinholmes.com
        - JustinHolmesMusic/blox-office
    - name: Add github repo remotes for justinholmes.com
      become_user: "{{os_username}}"
      become: yes
      shell: "git remote add {{item}} git@github.com:{{item}}/justinholmes.com.git; git fetch {{item}}"
      args:
        chdir: ~/projects/JustinHolmesMusic/justinholmes.com
      loop:
        - kubic71
        - jMyles
        - KPrasch
        - rjpartingtoniii
    - name: Add github repo remotes for blox-office
      become_user: "{{os_username}}"
      become: yes
      shell: "git remote add {{item}} git@github.com:{{item}}/blox-office`.git; git fetch {{item}}"
      args:
        chdir: ~/projects/JustinHolmesMusic/justinholmes.com
      loop:
        - kubic71
        - jMyles
